apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    namespace: log-and-ping
    name: log-and-ping-ingress
    labels:
        name: log-and-ping-ingress
spec:
    rules:
        - http:
              paths:
                  - path: /info
                    pathType: Prefix
                    backend:
                        service:
                            name: log-output-svc
                            port:
                                number: 3012
                  - path: /pingpong
                    pathType: Prefix
                    backend:
                        service:
                            name: ping-pong-svc
                            port:
                                number: 3011
