apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress-log
spec:
    rules:
        - http:
              paths:
                  - path: /info
                    pathType: Prefix
                    backend:
                        service:
                            name: log-output-svc
                            port:
                                number: 2345
