apiVersion: apps/v1
kind: Deployment
metadata:
    name: ping-pong
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ping-pong
    template:
        metadata:
            labels:
                app: ping-pong
        spec:
            volumes: # Define volume
                - name: shared-image
                  persistentVolumeClaim:
                      claimName: image-claim
            containers:
                - name: ping-pong
                  image: nikogenix/ping-pong:v3
                  resources:
                      limits:
                          memory: 512Mi
                          cpu: "1"
                  volumeMounts: # Mount volume
                      - name: shared-image
                        mountPath: /usr/src/app/files
