apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ping-pong
    labels:
        name: ping-pong
spec:
    rules:
        - http:
              paths:
                  - path: /pingpong
                    pathType: Prefix
                    backend:
                        service:
                            name: ping-pong-svc
                            port:
                                number: 3005
