apiVersion: v1
kind: Service
metadata:
    namespace: log-and-ping
    name: ping-pong-svc
spec:
    type: ClusterIP
    selector:
        app: ping-pong
    ports:
        - name: ping-pong
          protocol: TCP
          port: 3011
          targetPort: 3005
