apiVersion: apps/v1
kind: Deployment
metadata:
    name: project
spec:
    replicas: 1
    selector:
        matchLabels:
            app: project
    template:
        metadata:
            labels:
                app: project
        spec:
            containers:
                - name: project
                  image: nikogenix/project:v0.4
                  resources:
                      limits:
                          memory: 512Mi
                          cpu: "1"
