apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress-project
spec:
    rules:
        - http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: project-svc
                            port:
                                number: 2345
