apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    namespace: project
    name: project-ingress
    labels:
        name: project-ingress
spec:
    rules:
        - http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: project-frontend-svc
                            port:
                                number: 3021
                  - path: /api
                    pathType: Prefix
                    backend:
                        service:
                            name: project-backend-svc
                            port:
                                number: 3022
                  - path: /image.jpg
                    pathType: Prefix
                    backend:
                        service:
                            name: project-backend-svc
                            port:
                                number: 3022
