apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    namespace: project
    name: image-claim
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 200Mi
    volumeName: pv-project
