apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-project
spec:
    storageClassName: manual
    capacity:
        storage: 200Mi # Could be e.q. 500Gi. Small amount is to preserve space when testing locally
    volumeMode: Filesystem # This declares that it will be mounted into pods as a directory
    accessModes:
        - ReadWriteOnce
    local:
        path: /tmp/kube/project
    nodeAffinity: ## This is only required for local, it defines which nodes can access it
        required:
            nodeSelectorTerms:
                - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                            - k3d-k3s-default-agent-0
